### PR TITLE
Include BYON feature for jupyterhub component

### PR DESCRIPTION
**Pull request by harshad16**
Include BYON feature for jupyterhub component
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: https://github.com/open-services-group/byon/issues/20

Description:
https://github.com/open-services-group/byon/issues/20#issuecomment-1068145909

### CODE REVIEW

**Comment by harshad16** [comment]
/hold

wait for the image to be available in quay.

**Review by tumido — CHANGES_REQUESTED** [review]
Please cherry pick additional changes from https://github.com/opendatahub-io/odh-manifests/compare/v1.1.2...master

Odh Dashboard had additional permissions added, so any odh-dashboard container image built on top of master would fail to deploy with 1.1.2 manifests. 

In addition this should include https://github.com/opendatahub-io/odh-manifests/pull/549 as well.

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Pull request merged**
