### PR TITLE
add LF folks to owners

### PR DESCRIPTION
**Pull request by erikerlandson**
Signed-off-by: Erik Erlandson <eerlands@redhat.com>

### CODE REVIEW

**Comment by erikerlandson** [comment]
cc @lavlas

**Review by durandom — COMMENTED** [review]
/approve
/lgtm

**Review by durandom — APPROVED** [review]

**Comment by LaVLaS** [comment]
@erikerlandson Are you forking the older component manifests that have been migrated to [opendatahub-io-contrib/odh-contrib-manifests](https://github.com/opendatahub-io-contrib/odh-contrib-manifests)?

Since this is a fork of odh-manifests, would it be better to purge the opendatahub-io approvers/reviewers in favor of operator-first members?

**Comment by erikerlandson** [comment]
@LaVLaS  my fork is from `operate-first/odh-manifests`.  I find it confusing to keep track of the different forks here. There is at least:

- `operate-first/odh-manifests`
- `opendatahub-io/odh-manifests`
- `opendatahub-io-contrib/odh-contrib-manifests`

What should people in the operate first community be using for which purpose?

**Pull request merged**
